# Symlink this file to /etc/nginx/snippets/ssl-maneyko.com.conf
#
# vim: ft=nginx

listen 443 ssl;
listen [::]:443 ssl;
ssl_protocols TLSv1.3;

ssl_certificate     /etc/lego/certificates/maneyko.com.crt;
ssl_certificate_key /etc/lego/certificates/maneyko.com.key;

# https://raw.githubusercontent.com/certbot/certbot/refs/heads/main/certbot/src/certbot/_internal/plugins/nginx/tls_configs/options-ssl-nginx.conf
include snippets/options-ssl-nginx.conf;
# ssl_dhparam snippets/ssl-dhparams.pem;
