# Symlink this file to /etc/nginx/snippets/maneyko-ssl.conf
#
# vim: ft=nginx

listen 443 ssl;
listen [::]:443 ssl;
ssl_protocols TLSv1.3;

ssl_certificate     /etc/lego/certificates/maneyko.com.crt;
ssl_certificate_key /etc/lego/certificates/maneyko.com.key;

# https://raw.githubusercontent.com/certbot/certbot/HEAD/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
include /etc/letsencrypt/options-ssl-nginx.conf;
# ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
